### ISSUE TITLE
Create the Database Structure

### ISSUE THREAD

**Issue by Puliedro** [Puliedro/Facial_Recognition_Assistance_System#13]
We will use Docker to create a mongoDB database that will be connected to the mobile app and the Python Script.  To start testing the functionalities, we will need some queries that will create the basic structure of out database, so that we'll use it for other scripts and 

Initially, we need a table to store the students data. This should be named "students" and should include relevant information, such as:
```
    - idUser, to link the students in other tables.
    - Name
    - Surname
    - Last name
    - Email (Unique)
    - School ID (Unique)
    - Grade 
    - Group
    - Degree
```

There will have to be an "attendance" table, that will keep track of the attendance. The rows will be updated after the students successfully enter the current code. The table will include:
```
    - idAttendance
    - idUser (To link the student with their respective information)
    - Date and time (Timestamp)
    - Attendance (True/False)
```
    
Similarly, there has to be a table for the codes generated, named "codes", which would include:
```
    - idCode
    - Code
    - Time created
```

And lastly, there has to be another table for the attempts sent by the users in the app, named "codeattempts". If these happen to match the current last code, the attendance will be successfully added to the attendance table. This should include: 
```
    - idAttempt
    - idUser
    - email
    - code
    - attempt_time
```

**Branch: feature_karla**

**Useful resources:** 

- https://dev.mysql.com/doc/
- https://www.youtube.com/watch?v=3R_JWXn3O9I

**Comment by soniamendia** [comment]
"Creating_the_database_structure.sql" added to feature_karla branch as stated.

**Comment by KarlaDeAv** [comment]
"Populating students table.sql" added to feature_karla branch to complete the issue.
