### ISSUE TITLE
Code/PIN generator

### ISSUE THREAD

**Issue by Puliedro** [Puliedro/Facial_Recognition_Assistance_System#14]
Initially, the main algorithm will generate an alphanumeric code of length 4, which the students will have to enter in a future web app to get their attendance.  For now, we need the algorithm in Python that does this, with a modifiable amount of time for the intervals. When a code is generated, it will be updated in the respective "codes" table of the mongo database, so this script will have to connect to a test database first. 

**Libraries will have to be used:** 

```
- random
- string
- datetime
- time
```

**Branch: feature_priscila**

**Relevant URLS:**
https://www.youtube.com/watch?v=3vsC05rxZ8c
https://www.youtube.com/watch?v=rHTwjV1ORUQ

**Comment by PriscilaProgramer07** [comment]
"connector.py" was added to the feature_priscila branch as indicated.

**Comment by PriscilaProgramer07** [comment]
"main.py" was added to the feature_priscila branch as indicated.
